### ISSUE TITLE
Question about the Automotive HAT

### ISSUE THREAD

**Issue by MadeInPierre** [InnoRoute/RealtimeHAT#2]
Hello,

I am exploring the use of TSN for automotive applications. The Automotive RPi HAT seems interesting, and I would be curious to know what use cases you're aiming to cover with it. How would one use the Automotive HAT with a switch? Is there an existing automotive TSN switch solution available for purchase? If not, what other use cases are you imagining?

Thank you for your reply.

**Comment by ulbricht-inr** [comment]
Hi :)
thanks for your request in the Automotive version of our Real-Time HAT for Raspberry Pi.
It is derived from our basic (Gigabit Ethernet based) device which is well described:

Homepage: https://innoroute.com/realtimehat/
System Description: https://innoroute.com/download/systemdescription/
Operation Manual: https://github.com/InnoRoute/RealtimeHAT
Image download: https://my.hidrive.com/share/3ugldbuowd#$/
Pin Assignment: https://pinout.xyz/pinout/real_time_hat#
Instruction Videos: https://www.youtube.com/channel/UCX-0AXp_XrxDvd4bfO6ZMBQ
Papers: https://www.researchgate.net/project/Raspberry-Real-Time-HAT
HW extension AppStore: https://innoroute.com/hat_ext/
The Automotive version will have the same functionality, with one Gigabit PHY replaced by a SPE PHY of 100Mb/s:
[https://www.linkedin.com/feed/update/urn🇱🇮activity:6749237632544321536/](https://www.linkedin.com/feed/update/urn:li:activity:6749237632544321536/)
The Automotive version is fully designed, but not yet produced. Currently the FPGA chip is not available. Its availability has been shifted recently to July 2022. As soon as it will be announced we will ask for orders with fixed price. It will be around 500 EUR.

With best regards,
Andreas Foglar
