### ISSUE TITLE
Tx hardware timestamping

### ISSUE THREAD

**Issue by LaumiH** [InnoRoute/RealtimeHAT#3]
Hi,

I am a student and currently investigating into using the HAT as a TSN packet generator for a lab. While configuring and using ETF, MQPRIO and TAPRIO qdiscs works reasonably fine for me, I have problems with outgoing hardware timestamping.

The Pi/HAT successfully tags incoming packets with hardware timestamps, but outgoing packets do not receive timestamps (or so it seems). Let me explain my setup and code:

- Connect HAT `Port#1` and Pi `eth0` over LAN
- Connect `RT0` and my laptop over LAN, and let your laptop give an IP address to the Pi via dhcp
- Ssh onto Pi
- As I am mostly using [this code](https://gitlab.fokus.fraunhofer.de/pku/tsn-playground/-/blob/master/src/eth_stamps.c), it's a good starting point, as it does all the socket option config and worked for this thesis. Have a look at the `setup_l2_socket()` and `listen_for_txtstamps()` functions. 
- Execute it on the Pi as talker

If run as talker, the code *should* print the sent packets with their HW timestamps. The packets are sent, but no timestamps are printed, because the packet does not seem to be looped back to the socket's error queue, [as described here](https://docs.kernel.org/networking/timestamping.html#transmit-timestamps-with-msg-errqueue).

The code configures various socket options to enable HW timestamping, and I also enabled it for the interface via `SIOCSHWTSTAMP`.

Is there any experience on your side in HW tx timestamping on the HAT? The website says "Hardware-timestamping of all incoming and all marked outgoing frames" should be possible. Does marking frames mean anything different than what I did?

Many thanks!
Laura

**Comment by ulbricht-inr** [comment]
Hi, sorry for the late response...
in the past we discovered some missbehavior with to manny requested timestamps by the ptp4l settings. So we limit the timestamping additionally in the driver: https://github.com/InnoRoute/linux/blob/57e9c89947b071f2887337e5bdd6b208bbaf2839/net/dsa/tag_innoroute.c#L143
you can either send your packets with the ptpl2 ethertype, or register an other type in the driver.
