### ISSUE TITLE
Realtime HAT Time Sync both ports always faulty

### ISSUE THREAD

**Issue by anasbinmuslim** [InnoRoute/RealtimeHAT#7]
I am trying to configure Realtime HAT version 1.2 with the Build_rpi_image_545_image_2.01.zip. FPGA configuration and self test is successful, RT0 and RT2 are shown in ifconfig but as soon as ptp4l service starts, both ports always become FAULTY. As far as I understand, they should become MASTER if the ptp4l service is starting properly.
I have also tried with image version 528_image_2.00 and 400_image_1.00 but RT0, RT2 still becomes faulty as soon as ptp4l service starts. It doesn't matter if the RTHat is connected to another master device, slave device or whether it is not connected to anything, both ports show the same behavior.
Any tips on how to resolve this? The configuration of raspberrypi and RTHat was done according to the first steps page a few times and also according to the video on that page another time.
By the way, we have another RTHat v1.1 running image 400_image_1.00 from hidrive and it does not behave like this. It is working without any issues.

**Comment by ulbricht-inr** [comment]
hm, this might be an issue with the "new" kernel...

**Comment by anasbinmuslim** [comment]
The new kernel is only in the latest images i.e. 528, 545. Older images like 400 would still have old kernel. Isnt that correct? If yes, then this means if the new kernel is the issue, older image 400 should be working properly but it also puts both ports in Faulty state as soon as ptp4l starts.

**Comment by anasbinmuslim** [comment]
I tried the updated Bitstream for RTHat and ptp service works now. Ports by default assume Masters role and with another TSN device connected, ports also become slaves to other devices.
